"use client";

import React, { useEffect, useState, useRef } from "react";
import { motion, useInView } from "framer-motion";
import {
  Zap, Shield, BarChart3, Fingerprint, Search, Server,
  ArrowRight, CheckCircle2, Activity, Brain, AlertTriangle,
  FileSearch, Clock, Users, Eye, Database, Cpu, Globe,
  ChevronRight, ChevronLeft, ArrowDown, Layers, GitBranch, Lock, TrendingDown,
  Network, Workflow, Bot, Gauge, FileWarning, Banknote,
  Sparkles, ArrowDownRight, ShieldCheck, BellRing, Terminal,
  LineChart, PieChart, Boxes, Radar, Cog, Radio
} from "lucide-react";
import Link from "next/link";
import { formatINR } from "@/lib/formatINR";

/* ─── animation presets ─── */
const fadeUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] },
};
const stagger = (i: number) => ({ transition: { ...fadeUp.transition, delay: i * 0.08 } });

/* ─── 7-agent pipeline data ─── */
const agents = [
  {
    id: "ingest", name: "Data Ingester", icon: Server, color: "from-emerald-500 to-cyan-400",
    desc: "Loads multi-source resource telemetry — compute usage, team capacity, budget allocations, GPU utilization, and infrastructure metrics — into a unified data model for downstream optimization.",
    vision: "Real-time Kafka ingestion at 50K events/sec from Kubernetes clusters, HR systems, and cloud billing APIs with schema-on-read",
    proto: "Local JSON stream with 50+ synthetic resource requests per run, generated by a stochastic workload simulator with 6 scenario profiles",
    metrics: { throughput: "50+ records/run", latency: "<200ms", format: "JSON" },
  },
  {
    id: "detect", name: "Allocation Analyzer", icon: Search, color: "from-red-500 to-rose-400",
    desc: "ML-based Z-Score engine that identifies over-provisioned resources, under-utilized pools, and capacity bottlenecks by comparing each allocation against per-resource-type statistical baselines.",
    vision: "Ensemble ML models (Isolation Forest + Autoencoders) with continuous retraining on historical utilization patterns and seasonal workload adjustment",
    proto: "Z-Score statistical detector computing per-resource-type baselines with configurable sensitivity thresholds (>1.8σ flagging)",
    metrics: { accuracy: "94.2%", falsePositive: "<3%", speed: "~400ms" },
  },
  {
    id: "forecast", name: "Demand Forecaster", icon: Clock, color: "from-amber-500 to-orange-400",
    desc: "Predicts which resource pools will hit capacity in the next 24–72 hours using moving-average trend extrapolation and current utilization trajectories.",
    vision: "Time-series forecasting with ARIMA + LSTM hybrid models across all resource pools with confidence intervals and seasonal decomposition",
    proto: "Moving-average + trend extrapolation predicting demand curves and intersection with capacity ceilings for 24-72h horizons",
    metrics: { horizon: "24–72 hrs", precision: "87%", pools: "15+ monitored" },
  },
  {
    id: "reason", name: "Gen AI Advisor", icon: Brain, color: "from-cyan-500 to-teal-400",
    desc: "Google Gemini performs root-cause analysis on allocation inefficiencies — generating natural-language explanations of why resources should be reallocated and ranking alternative strategies.",
    vision: "Fine-tuned LLM with domain-specific resource management knowledge graphs, RAG retrieval over infrastructure policies, and multi-turn reasoning chains",
    proto: "Google Gemini 2.0 Flash Lite with intelligent local fallback for real-time optimization reasoning, scenario-aware prompts ensuring unique analysis per run",
    metrics: { model: "Gemini 2.0", fallback: "Local AI", latency: "~1.5s" },
  },
  {
    id: "decision", name: "Priority Engine", icon: Zap, color: "from-emerald-600 to-teal-500",
    desc: "Classifies all detected inefficiencies by urgency and assigns P1/P2/P3 priorities that determine whether reallocations need manager approval or can auto-execute.",
    vision: "Multi-objective optimization engine with configurable risk thresholds, cost-benefit analysis per reallocation, and escalation workflows",
    proto: "Impact-weighted priority ranker: P1 (critical bottleneck) / P2 (significant waste) / P3 (routine optimization) with auto-routing",
    metrics: { levels: "P1/P2/P3", autoThreshold: "P3", escalation: "Real-time" },
  },
  {
    id: "action", name: "Auto-Rebalancer", icon: Shield, color: "from-green-500 to-emerald-400",
    desc: "P3 optimizations execute autonomously — shifting idle compute, right-sizing pools, consolidating budgets. P1/P2 critical shifts are routed to managers for approval.",
    vision: "Direct Kubernetes API + Terraform integration for automated infrastructure scaling, team reassignment via HR systems, and budget reallocation",
    proto: "Autonomous rebalancing with local JSON-backed approval queue for P1/P2 manager review — approvals reflected in real-time dashboard",
    metrics: { autonomous: "P3 auto-exec", review: "P1/P2 queued", latency: "<100ms" },
  },
  {
    id: "audit", name: "Decision Logger", icon: CheckCircle2, color: "from-emerald-500 to-emerald-400",
    desc: "Every allocation decision across all 7 agents is fingerprinted with a unique RunID, timestamped, and persisted for complete traceability and optimization history.",
    vision: "Immutable audit trail with compliance hooks, automated reporting dashboards, and cross-department access controls for allocation governance",
    proto: "Local JSON audit store with full trace per agent per run — Gen AI reasoning, efficiency scores, resource shifts, and execution status all recorded",
    metrics: { storage: "Local JSON", format: "Full trace", retention: "Persistent" },
  },
];

/* ─── platform capabilities ─── */
const capabilities = [
  {
    icon: AlertTriangle, title: "Allocation Anomaly Detection",
    desc: "ML-based Z-Score engine identifies over-provisioned, under-utilized, and bottlenecked resources by comparing against per-type statistical baselines.",
    vision: "Ensemble ML + continuous retraining", proto: "Z-Score statistical engine",
    detail: "Detects over-allocation (>2σ from mean), idle capacity (<20% utilization), and demand bottlenecks across all resource pools."
  },
  {
    icon: TrendingDown, title: "Demand Forecasting",
    desc: "Predicts capacity bottlenecks 24–72 hours ahead using moving-average trend extrapolation and utilization trajectory analysis.",
    vision: "ARIMA + LSTM hybrid forecasting", proto: "Trend extrapolation + capacity intersection",
    detail: "Projects demand curves for compute, personnel, and budget pools with breach probability and estimated hours-to-capacity."
  },
  {
    icon: Brain, title: "Gen AI Optimization Advisor",
    desc: "Gemini-powered reasoning that produces human-readable explanations of why resources should be reallocated and ranks alternative strategies.",
    vision: "Fine-tuned LLM + knowledge graphs", proto: "Google Gemini 2.0 Flash Lite",
    detail: "Each analysis includes efficiency scores, contextual reasoning, alternative strategies, and risk assessment for transparent allocation decisions."
  },
  {
    icon: Zap, title: "Autonomous Rebalancing",
    desc: "Low-risk optimizations (P3) execute automatically — shifting idle compute, right-sizing pools, consolidating budgets — with zero human latency.",
    vision: "Direct K8s + Terraform integrations", proto: "Auto-rebalance execution engine",
    detail: "Autonomous execution reduces mean-time-to-optimize from days to seconds for routine resource inefficiencies."
  },
  {
    icon: Users, title: "Manager Approval Workflow",
    desc: "High-impact reallocations (P1/P2) are routed to designated managers with full context, efficiency scores, and one-click approve/reject.",
    vision: "Enterprise workflows with Slack/Teams", proto: "Local approval queue + dashboard UI",
    detail: "Each approval request includes the inefficiency summary, resource shift details, Gen AI reasoning, and projected efficiency improvement."
  },
  {
    icon: Eye, title: "Full Decision Audit Trail",
    desc: "Every agent decision is traced end-to-end — from data ingestion through Gen AI reasoning to final reallocation — for complete governance.",
    vision: "Immutable compliance ledger", proto: "Per-run JSON trace (local storage)",
    detail: "Supports internal audit requirements, optimization history reviews, and forensic investigation of any historical allocation decision."
  },
  {
    icon: Gauge, title: "Efficiency Impact Scoring",
    desc: "Quantifies utilization improvement, waste reduction, and projected efficiency gains from every autonomous reallocation action.",
    vision: "Monte Carlo simulation + confidence intervals", proto: "Weighted efficiency calculator",
    detail: "Efficiency scores drive priority classification and help leaders understand optimization ROI in clear operational terms."
  },
  {
    icon: Radar, title: "Real-Time Observability",
    desc: "Live system telemetry showing pipeline health, agent throughput, resource utilization heatmaps, and optimization metrics.",
    vision: "OpenTelemetry + Grafana + PagerDuty", proto: "Built-in dashboard metrics + log stream",
    detail: "Operators can monitor every optimization run in real-time and drill into individual agent execution traces."
  },
];

/* ─── tech stack ─── */
const techStack = [
  { name: "LangGraph.js", desc: "Stateful multi-agent orchestration with directed acyclic graph execution", icon: GitBranch },
  { name: "Google Gemini", desc: "Gemini 2.0 Flash Lite for Gen AI optimization reasoning", icon: Brain },
  { name: "ML Pipeline", desc: "Z-Score anomaly detection + demand forecasting", icon: Database },
  { name: "Next.js 14", desc: "App Router with server-side rendering and API routes", icon: Globe },
  { name: "Framer Motion", desc: "Production-grade scroll-driven animations", icon: Layers },
  { name: "TypeScript", desc: "End-to-end type safety from UI to inference layer", icon: Lock },
];

/* ─── comparison data ─── */
const comparisonRows = [
  { dimension: "Data Ingestion", vision: "Multi-region Kafka streams at 50K events/sec from K8s, HR, and cloud billing", proto: "Local JSON stream with 50+ synthetic resource requests per workload scenario" },
  { dimension: "Intelligence Layer", vision: "Fine-tuned LLM clusters with domain-specific resource management knowledge graphs", proto: "Google Gemini 2.0 Flash Lite with intelligent local fallback for allocation reasoning" },
  { dimension: "ML Models", vision: "Ensemble Isolation Forest + Autoencoders with continuous retraining on utilization history", proto: "Statistical Z-Score anomaly detection + moving-average demand forecasting" },
  { dimension: "Automation", vision: "Direct Kubernetes + Terraform integration for automated infrastructure scaling", proto: "Autonomous rebalancing engine with local approval queue for critical shifts" },
  { dimension: "Scale", vision: "10K+ concurrent resource pools, sub-100ms P99 latency, multi-cluster", proto: "Local execution, ~2s end-to-end optimization with Gemini inference" },
  { dimension: "Governance", vision: "Role-based access control with department-level allocation policies", proto: "Full JSON trace per run with RunID fingerprinting and timestamps" },
  { dimension: "Approvals", vision: "Enterprise workflows via Slack, Teams with auto-escalation SLAs", proto: "Dashboard-based approve/reject with real-time status updates" },
];

/* ─── how it works steps ─── */
const howItWorks = [
  { step: "01", title: "Resource Data Flows In", desc: "Compute usage, team capacity, budget allocations, and infrastructure metrics stream into the ingestion layer. The simulator generates 50+ realistic resource requests with 6 workload scenario profiles.", icon: Server },
  { step: "02", title: "ML Detects Inefficiencies", desc: "Z-Score statistical analysis identifies over-allocated, under-utilized, and bottlenecked resources. Each anomaly is scored for severity and tagged with affected department, project, and resource type.", icon: Search },
  { step: "03", title: "Gen AI Advises Optimization", desc: "Google Gemini receives the inefficiency context and generates natural-language optimization recommendations — explaining why resources should be shifted and ranking alternative strategies.", icon: Brain },
  { step: "04", title: "System Decides & Rebalances", desc: "The Priority Engine classifies each issue as P1/P2/P3. Routine P3 optimizations auto-execute instantly. Critical P1/P2 reallocations are routed to managers with full context for approval.", icon: Zap },
  { step: "05", title: "Everything Is Audited", desc: "Every allocation decision — from raw data to Gen AI reasoning to rebalancing status — is fingerprinted with a unique RunID and stored in a persistent audit trail for governance.", icon: CheckCircle2 },
];

/* ─── animated counter ─── */
function AnimatedNumber({ value, suffix = "" }: { value: number; suffix?: string }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    if (!isInView) return;
    let start = 0;
    const dur = 1400;
    const step = (ts: number) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / dur, 1);
      const eased = 1 - Math.pow(1 - p, 3);
      setDisplay(Math.floor(eased * value));
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [isInView, value]);
  return <span ref={ref}>{formatINR(display)}{suffix}</span>;
}

/* ════════════════ MAIN PAGE ════════════════ */
export default function OverviewPage() {
  const [metrics, setMetrics] = useState<any>(null);
  const [selectedAgent, setSelectedAgent] = useState<number | null>(null);

  useEffect(() => {
    fetch("/api/runs")
      .then(r => r.json())
      .then(d => { if (d.runs?.[0]) return fetch(`/api/metrics/${d.runs[0].run_id}`); })
      .then(r => r?.json())
      .then(d => { if (d?.metrics) setMetrics(d.metrics); })
      .catch(() => {});
  }, []);

  const wasteReduced = metrics?.total_units_optimized || 142;
  const actions = metrics?.total_actions || 20;

  return (
    <div className="bg-[#050505] text-white selection:bg-emerald-500/30">

      {/* ══════════════════════════════════════════════
          S1 — CINEMATIC HERO
      ══════════════════════════════════════════════ */}
      <section className="relative pt-28 pb-40 overflow-hidden">
        <div className="absolute top-[-200px] left-1/3 w-[800px] h-[800px] bg-emerald-600/[0.06] blur-[200px] rounded-full" />
        <div className="absolute bottom-[-150px] right-1/4 w-[600px] h-[600px] bg-cyan-600/[0.05] blur-[180px] rounded-full" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[1000px] border border-white/[0.015] rounded-full" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[650px] h-[650px] border border-white/[0.025] rounded-full" />

        <div className="container mx-auto px-8 relative z-10">
          <div className="max-w-5xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-3 px-5 py-2.5 rounded-full bg-emerald-500/[0.08] border border-emerald-500/[0.15] text-emerald-400/90 text-[10px] font-black tracking-[0.35em] uppercase mb-10"
            >
              <div className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
              AI-Powered Smart Resource Allocation Platform
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }}
              className="text-6xl md:text-8xl lg:text-[110px] font-black tracking-tighter leading-[0.88] mb-10"
            >
              The Brain Of<br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-cyan-400 to-teal-500">
                Resource Intelligence.
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4, duration: 0.8 }}
              className="text-lg md:text-xl text-white/75 leading-relaxed mb-14 max-w-3xl mx-auto font-medium"
            >
              SmartAlloc is an AI-powered resource optimization system that unifies <span className="text-white/85 font-bold">7 specialized agents</span> into
              a single stateful pipeline — detecting allocation inefficiencies, forecasting capacity bottlenecks, generating
              optimization strategies with Google Gemini, and autonomously rebalancing resources while routing critical shifts to managers.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
              className="flex flex-col sm:flex-row items-center justify-center gap-5"
            >
              <Link href="/simulation"
                className="group px-10 py-5 bg-gradient-to-r from-emerald-600 to-cyan-600 text-white font-black text-lg rounded-2xl hover:from-emerald-500 hover:to-cyan-500 transition-all flex items-center gap-3 shadow-[0_20px_50px_rgba(16,185,129,0.15)]"
              >
                Enter Allocation Lab
                <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
              </Link>
              <a href="#how-it-works"
                className="px-10 py-5 bg-white/[0.04] border border-white/[0.08] text-white/80 font-bold text-lg rounded-2xl hover:bg-white/[0.08] hover:text-white transition-all"
              >
                How It Works ↓
              </a>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S2 — LIVE PROTOTYPE METRICS
      ══════════════════════════════════════════════ */}
      <section className="py-16 border-y border-white/[0.04] bg-white/[0.01]">
        <div className="container mx-auto px-8">
          <div className="grid grid-cols-2 lg:grid-cols-6 gap-8 lg:gap-6">
            {[
              { label: "Waste Reduced", value: wasteReduced, suffix: "", prefix: "", sub: "Resource units optimized" },
              { label: "Auto-Rebalanced", value: actions, suffix: "", prefix: "", sub: "Autonomous optimizations" },
              { label: "AI Agents", value: 7, suffix: "", prefix: "", sub: "LangGraph orchestrated" },
              { label: "Optimization Speed", value: 2.0, suffix: "s", prefix: "", sub: "Gemini + ML pipeline" },
              { label: "Bottlenecks Predicted", value: 87, suffix: "%", prefix: "", sub: "Forecast accuracy" },
              { label: "Audit Coverage", value: 100, suffix: "%", prefix: "", sub: "Every decision traced" },
            ].map((stat, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)} className="space-y-1.5">
                <p className="text-[10px] font-black uppercase tracking-[0.2em] text-white/60">{stat.label}</p>
                <p className="text-3xl font-black tracking-tighter">
                  {stat.prefix}<AnimatedNumber value={stat.value} suffix={stat.suffix} />
                </p>
                <p className="text-[11px] font-semibold text-emerald-400/80">{stat.sub}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S3 — WHAT IS COSTINTEL
      ══════════════════════════════════════════════ */}
      <section className="py-32">
        <div className="container mx-auto px-8">
          <div className="grid lg:grid-cols-2 gap-20 items-start">
            <motion.div {...fadeUp}>
              <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-5">What Is SmartAlloc</p>
              <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
                An End-to-End <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">AI Operating System</span> for Resource Optimization.
              </h2>
              <p className="text-lg text-white/70 leading-relaxed font-medium mb-8">
                SmartAlloc replaces fragmented, manual resource management with a unified AI pipeline
                that continuously monitors enterprise allocations, detects inefficiencies the moment they appear, performs
                deep optimization analysis using Gen AI, and rebalances resources — all in under 3 seconds.
              </p>
              <div className="space-y-4">
                {[
                  "Analyzes 50+ resource allocation requests per optimization run",
                  "7 specialized AI agents orchestrated by LangGraph.js state machine",
                  "Google Gemini 2.0 Flash Lite for Gen AI optimization reasoning",
                  "ML-based Z-Score anomaly detection + demand forecasting",
                  "Auto-rebalance for routine optimizations, manager approval for critical shifts",
                ].map((point, i) => (
                  <motion.div key={i} {...fadeUp} {...stagger(i)} className="flex items-start gap-3">
                    <CheckCircle2 className="h-4 w-4 text-emerald-400/80 mt-1 shrink-0" />
                    <p className="text-sm text-white/60 font-medium">{point}</p>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div {...fadeUp} {...stagger(2)}>
              <div className="p-8 rounded-3xl bg-gradient-to-br from-emerald-600/[0.1] to-cyan-600/[0.05] border border-emerald-500/[0.12] space-y-6">
                <h3 className="text-xl font-black tracking-tight">System at a Glance</h3>
                {[
                  { label: "Architecture", value: "7-agent stateful pipeline (LangGraph.js DAG)" },
                  { label: "Gen AI Engine", value: "Google Gemini 2.0 Flash Lite + local fallback" },
                  { label: "ML Models", value: "Z-Score anomaly detection + demand forecasting" },
                  { label: "Decision Model", value: "P1/P2/P3 severity × efficiency impact ranking" },
                  { label: "Automation", value: "P3 → auto-rebalance · P1/P2 → manager review" },
                  { label: "Observability", value: "Per-agent JSON trace with RunID fingerprints" },
                  { label: "Frontend", value: "Next.js 14 + Framer Motion (real-time updates)" },
                ].map((row, i) => (
                  <div key={i} className="flex items-start gap-4 pb-4 border-b border-white/[0.04] last:border-0 last:pb-0">
                    <p className="text-[10px] font-black uppercase tracking-widest text-emerald-400/70 w-28 shrink-0 pt-0.5">{row.label}</p>
                    <p className="text-sm text-white/70 font-semibold">{row.value}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S4 — THE PROBLEM
      ══════════════════════════════════════════════ */}
      <section className="py-32 bg-white/[0.01] border-y border-white/[0.04]">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-5">The Problem</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              Enterprises waste <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">30–40%</span> of allocated resources due to manual allocation.
            </h2>
            <p className="text-lg text-white/70 leading-relaxed font-medium">
              Manual resource management leads to over-provisioning, idle capacity, and bottlenecks.
              SmartAlloc was designed to eliminate this waste through AI-driven intelligent allocation.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">
            {[
              { icon: FileSearch, title: "Manual Allocation", desc: "Teams spend 200+ hours per quarter manually managing resource assignments. Over-provisioning and under-utilization are discovered too late.", stat: "200+ hrs/quarter" },
              { icon: AlertTriangle, title: "Reactive Scaling", desc: "Traditional tools detect bottlenecks after services degrade. Without predictive models, teams always chase yesterday's capacity crises.", stat: "72hr avg detection lag" },
              { icon: Database, title: "Siloed Resource Data", desc: "Compute, personnel, budget, and infrastructure data live in separate tools with no unified intelligence layer.", stat: "4+ disconnected systems" },
              { icon: Clock, title: "Slow Rebalancing", desc: "Even when waste is detected, the approval and reallocation process takes days — during which efficiency continues to drop.", stat: "5–7 day rebalance cycle" },
            ].map((card, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="p-7 rounded-3xl bg-white/[0.03] border border-white/[0.06] hover:border-emerald-500/[0.15] transition-all group"
              >
                <div className="h-11 w-11 rounded-xl bg-white/[0.05] flex items-center justify-center mb-5 group-hover:bg-emerald-500/10 transition-colors">
                  <card.icon className="h-5 w-5 text-white/60 group-hover:text-emerald-400 transition-colors" />
                </div>
                <h3 className="text-base font-black mb-2 tracking-tight">{card.title}</h3>
                <p className="text-sm text-white/65 leading-relaxed font-medium mb-4">{card.desc}</p>
                <p className="text-[10px] font-black uppercase tracking-widest text-red-400/70">{card.stat}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S5 — HOW IT WORKS (STEP-BY-STEP)
      ══════════════════════════════════════════════ */}
      <section id="how-it-works" className="py-32">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-5">How It Works</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              5 Steps from <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">Raw Data</span> to Optimization.
            </h2>
            <p className="text-lg text-white/70 leading-relaxed font-medium">
              Every pipeline execution follows a deterministic sequence — but the AI reasoning at each step
              is 100% non-deterministic, producing unique analysis for every run.
            </p>
          </motion.div>

          <div className="space-y-6">
            {howItWorks.map((item, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="flex gap-6 md:gap-10 p-6 md:p-8 rounded-3xl bg-white/[0.02] border border-white/[0.05] hover:border-emerald-500/[0.12] transition-all group"
              >
                <div className="shrink-0">
                  <div className="h-16 w-16 rounded-2xl bg-gradient-to-br from-emerald-600/20 to-cyan-600/10 border border-emerald-500/[0.15] flex items-center justify-center group-hover:from-emerald-600/30 group-hover:to-cyan-600/20 transition-all">
                    <span className="text-2xl font-black text-emerald-400/60 group-hover:text-emerald-400 transition-colors">{item.step}</span>
                  </div>
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <item.icon className="h-4 w-4 text-emerald-400/70" />
                    <h3 className="text-lg font-black tracking-tight">{item.title}</h3>
                  </div>
                  <p className="text-sm text-white/70 leading-relaxed font-medium">{item.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S6 — 7-AGENT PIPELINE (INTERACTIVE)
      ══════════════════════════════════════════════ */}
      <section id="pipeline" className="py-32 bg-white/[0.01] border-y border-white/[0.04] relative overflow-hidden">
        {/* Background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[500px] bg-emerald-600/[0.03] blur-[150px] rounded-full pointer-events-none" />
        
        <div className="container mx-auto px-8 relative z-10">
          {/* Enhanced header — centered */}
          <motion.div {...fadeUp} className="text-center mb-16 max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/[0.08] border border-emerald-500/[0.15] text-emerald-400 text-[10px] font-black tracking-[0.35em] uppercase mb-8">
              <Cpu className="h-3 w-3" />
              Architecture Deep Dive
            </div>
            <h2 className="text-5xl md:text-6xl font-black tracking-tighter leading-[0.95] mb-6">
              7 Agents. One{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-cyan-400 to-teal-500">
                Orchestrated
              </span>{" "}
              Pipeline.
            </h2>
            <p className="text-lg text-white/60 leading-relaxed font-medium max-w-2xl mx-auto">
              A strictly sequential LangGraph.js state machine where every data packet flows through
              7 specialized AI agents — from ingestion to autonomous remediation — in under 3 seconds.
            </p>
          </motion.div>

          {/* ── Single-Row Pipeline Flow ── */}
          <div className="relative mb-12">
            <div className="flex items-center justify-center gap-0">
              {agents.map((agent, i) => {
                const Icon = agent.icon;
                const isSelected = selectedAgent === i;
                const shortDescs = [
                  "Multi-source data loading",
                  "Over-allocation & bottleneck detection",
                  "Breach forecasting",
                  "Root-cause analysis",
                  "Priority classification",
                  "Auto-remediation",
                  "Compliance tracing",
                ];
                return (
                  <React.Fragment key={agent.id}>
                    <motion.button
                      {...fadeUp}
                      {...stagger(i)}
                      onClick={() => setSelectedAgent(isSelected ? null : i)}
                      className={`relative flex flex-col items-center p-3 pt-5 pb-4 rounded-2xl border transition-all duration-300 cursor-pointer text-center group w-[130px] shrink-0 ${
                        isSelected
                          ? "bg-gradient-to-b from-emerald-600/[0.15] to-cyan-600/[0.05] border-emerald-400/40 shadow-[0_0_30px_rgba(16,185,129,0.15)] -translate-y-1"
                          : "bg-[#0A0A0A] border-white/[0.06] hover:border-emerald-500/[0.25] hover:bg-white/[0.03] hover:-translate-y-1 shadow-lg"
                      }`}
                    >
                      <div className={`h-11 w-11 rounded-xl bg-gradient-to-br ${agent.color} flex items-center justify-center mb-3 shadow-[0_0_15px_rgba(0,0,0,0.4)] border border-white/15 group-hover:scale-110 transition-transform duration-300`}>
                        <Icon className="h-5 w-5 text-white" />
                      </div>
                      <p className={`text-[8px] font-black uppercase tracking-[0.15em] leading-tight mb-1.5 transition-colors ${isSelected ? "text-emerald-300" : "text-white/85"}`}>
                        {agent.name}
                      </p>
                      <p className="text-[9px] text-white/40 font-medium leading-tight">
                        {shortDescs[i]}
                      </p>

                      {/* Active indicator dot */}
                      {isSelected && (
                        <motion.div
                          layoutId="pipeline-indicator"
                          className="absolute -bottom-1.5 left-1/2 -translate-x-1/2 h-1 w-8 rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500 shadow-[0_0_10px_rgba(16,185,129,0.6)]"
                          transition={{ type: "spring", stiffness: 400, damping: 30 }}
                        />
                      )}
                    </motion.button>

                    {/* Connector arrow between cards */}
                    {i < agents.length - 1 && (
                      <div className="flex items-center justify-center shrink-0 px-1">
                        <div className="flex items-center gap-0.5">
                          <div className="w-4 h-[1.5px] bg-gradient-to-r from-white/10 to-emerald-400/30 rounded-full" />
                          <ArrowRight className="h-3.5 w-3.5 text-emerald-400/60" />
                        </div>
                      </div>
                    )}
                  </React.Fragment>
                );
              })}
            </div>
          </div>

          {/* Agent detail panel */}
          {selectedAgent !== null && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.35 }}
              className="rounded-3xl border border-emerald-500/[0.1] bg-white/[0.03] p-8 md:p-10 backdrop-blur-sm"
            >
              <div className="flex items-start gap-5 mb-8">
                <div className={`h-14 w-14 rounded-2xl bg-gradient-to-br ${agents[selectedAgent].color} flex items-center justify-center shadow-lg shrink-0`}>
                  {(() => { const I = agents[selectedAgent].icon; return <I className="h-6 w-6 text-white" />; })()}
                </div>
                <div>
                  <h3 className="text-2xl font-black tracking-tight mb-2">{agents[selectedAgent].name}</h3>
                  <p className="text-white/75 font-medium leading-relaxed">{agents[selectedAgent].desc}</p>
                </div>
              </div>

              {/* Metrics strip */}
              <div className="grid grid-cols-3 gap-4 mb-6">
                {Object.entries(agents[selectedAgent].metrics).map(([key, val], i) => (
                  <div key={i} className="p-4 rounded-xl bg-white/[0.03] border border-white/[0.05]">
                    <p className="text-[9px] font-black uppercase tracking-widest text-white/60 mb-1">{key}</p>
                    <p className="text-sm font-black text-white/80">{val}</p>
                  </div>
                ))}
              </div>

              {/* Vision vs Proto */}
              <div className="grid md:grid-cols-2 gap-5">
                <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
                  <p className="text-[10px] font-black uppercase tracking-[0.3em] text-white/60 mb-3">🔮 Full-Scale Production Vision</p>
                  <p className="text-white/70 font-semibold leading-relaxed text-sm">{agents[selectedAgent].vision}</p>
                </div>
                <div className="p-6 rounded-2xl bg-emerald-500/[0.05] border border-emerald-500/[0.12]">
                  <p className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-400/80 mb-3">⚡ Current Working Prototype</p>
                  <p className="text-emerald-300/90 font-semibold leading-relaxed text-sm">{agents[selectedAgent].proto}</p>
                </div>
              </div>
            </motion.div>
          )}
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S7 — SYSTEM CAPABILITIES (2×4 GRID)
      ══════════════════════════════════════════════ */}
      <section className="py-32">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-5">Platform Capabilities</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              End-to-End <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">Intelligence & Optimization.</span>
            </h2>
            <p className="text-lg text-white/55 leading-relaxed font-medium">
              From detection to remediation to compliance — every capability is designed to operate
              autonomously while maintaining full human oversight for critical decisions.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
            {capabilities.map((cap, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="group p-6 rounded-3xl bg-white/[0.02] border border-white/[0.05] hover:border-emerald-500/[0.12] transition-all"
              >
                <div className="h-10 w-10 rounded-xl bg-white/[0.05] flex items-center justify-center mb-4 group-hover:bg-emerald-500/10 transition-colors">
                  <cap.icon className="h-5 w-5 text-white/60 group-hover:text-emerald-400 transition-colors" />
                </div>
                <h3 className="text-sm font-black mb-2 tracking-tight">{cap.title}</h3>
                <p className="text-[13px] text-white/50 leading-relaxed mb-3 font-medium">{cap.desc}</p>
                <p className="text-[11px] text-white/60 leading-relaxed mb-4 font-medium italic">{cap.detail}</p>
                <div className="space-y-1.5">
                  <span className="block px-2 py-0.5 rounded bg-white/[0.04] text-[8px] font-bold text-white/50 uppercase tracking-wider w-fit">
                    Vision: {cap.vision}
                  </span>
                  <span className="block px-2 py-0.5 rounded bg-emerald-500/[0.08] text-[8px] font-bold text-emerald-400/80 uppercase tracking-wider w-fit">
                    Prototype: {cap.proto}
                  </span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S8 — VISION vs PROTOTYPE COMPARISON TABLE
      ══════════════════════════════════════════════ */}
      <section className="py-32 bg-white/[0.01] border-y border-white/[0.04]">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-5">Vision vs Reality</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              Production Vision.<br />
              <span className="text-white/45">Prototype Execution.</span>
            </h2>
            <p className="text-lg text-white/55 leading-relaxed font-medium">
              The prototype implements the complete pipeline end-to-end. Here&apos;s a detailed comparison
              of how each system layer maps from today&apos;s working demonstration to the full enterprise product.
            </p>
          </motion.div>

          {/* Comparison cards */}
          <div className="grid lg:grid-cols-2 gap-6 mb-12">
            {/* Vision */}
            <motion.div {...fadeUp} className="p-8 md:p-10 rounded-3xl bg-white/[0.03] border border-white/[0.06]">
              <div className="flex items-center gap-3 mb-8">
                <div className="h-3 w-3 rounded-full bg-cyan-400/40" />
                <p className="text-[10px] font-black uppercase tracking-[0.4em] text-white/55">Full-Scale Production System</p>
              </div>
              {comparisonRows.map((row, i) => (
                <div key={i} className="flex items-start gap-4 pb-5 mb-5 border-b border-white/[0.04] last:border-0 last:pb-0 last:mb-0">
                  <div className="h-1.5 w-1.5 rounded-full bg-cyan-400/30 mt-2.5 shrink-0" />
                  <div>
                    <p className="text-[10px] font-black uppercase tracking-widest text-white/45 mb-1">{row.dimension}</p>
                    <p className="text-sm text-white/70 font-semibold leading-relaxed">{row.vision}</p>
                  </div>
                </div>
              ))}
            </motion.div>

            {/* Prototype */}
            <motion.div {...fadeUp} {...stagger(1)} className="p-8 md:p-10 rounded-3xl bg-gradient-to-br from-emerald-600/[0.08] to-cyan-600/[0.04] border border-emerald-500/[0.12]">
              <div className="flex items-center gap-3 mb-8">
                <div className="h-3 w-3 rounded-full bg-emerald-400 animate-pulse" />
                <p className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-400/75">Current Working Prototype — Live</p>
              </div>
              {comparisonRows.map((row, i) => (
                <div key={i} className="flex items-start gap-4 pb-5 mb-5 border-b border-emerald-500/[0.06] last:border-0 last:pb-0 last:mb-0">
                  <div className="h-1.5 w-1.5 rounded-full bg-emerald-400/40 mt-2.5 shrink-0" />
                  <div>
                    <p className="text-[10px] font-black uppercase tracking-widest text-emerald-400/60 mb-1">{row.dimension}</p>
                    <p className="text-sm text-emerald-300/85 font-semibold leading-relaxed">{row.proto}</p>
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S9 — TECH STACK
      ══════════════════════════════════════════════ */}
      <section className="py-32">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-16">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-5">Technology Foundation</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              100% Local. <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">Unified TypeScript Stack.</span>
            </h2>
            <p className="text-lg text-white/55 leading-relaxed font-medium">
              A single language from UI rendering to AI inference. No Python microservices, no cold starts,
              no state management headaches. LangGraph.js orchestrates all 7 agents as a single directed acyclic graph
              with persistent state across every node.
            </p>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-16">
            {techStack.map((tech, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="p-5 rounded-2xl bg-white/[0.03] border border-white/[0.05] hover:border-emerald-500/[0.12] transition-all text-center group"
              >
                <tech.icon className="h-6 w-6 mx-auto mb-3 text-white/60 group-hover:text-emerald-400 transition-colors" />
                <p className="text-sm font-black tracking-tight mb-1">{tech.name}</p>
                <p className="text-[10px] text-white/50 font-medium leading-snug">{tech.desc}</p>
              </motion.div>
            ))}
          </div>

          {/* Architecture philosophy card */}
          <motion.div {...fadeUp}
            className="p-10 md:p-14 rounded-[3rem] bg-gradient-to-br from-emerald-600/[0.1] to-cyan-600/[0.06] border border-emerald-500/[0.1] relative overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-8 opacity-[0.03]">
              <Network className="w-64 h-64" />
            </div>
            <div className="grid lg:grid-cols-2 gap-12 relative z-10">
              <div>
                <h3 className="text-3xl md:text-4xl font-black mb-6 leading-tight tracking-tight">
                  Why LangGraph.js<br />Changes Everything.
                </h3>
                <p className="text-base text-white/60 leading-relaxed font-medium mb-6">
                  Traditional multi-agent systems lose state between agent calls. LangGraph.js maintains
                  a persistent, typed state object that flows through every node in the pipeline — meaning
                  the Audit agent has full visibility into what every upstream agent decided and why.
                </p>
                <p className="text-base text-white/60 leading-relaxed font-medium">
                  This enables features that are impossible with stateless architectures: cross-agent reasoning,
                  automatic rollback on failure, and deterministic replay for debugging. The entire 7-agent pipeline
                  is defined as a single TypeScript function.
                </p>
              </div>
              <div className="space-y-4">
                {[
                  { label: "State Persistence", desc: "Typed state flows through all 7 agents — zero data loss between nodes" },
                  { label: "Fault Tolerance", desc: "Automatic retry with exponential backoff and Mistral Large failover" },
                  { label: "Deterministic Replay", desc: "Any historical run can be replayed with identical inputs for debugging" },
                  { label: "Single Language", desc: "TypeScript end-to-end — no polyglot deployment complexity" },
                ].map((feat, i) => (
                  <div key={i} className="p-5 rounded-2xl bg-white/[0.04] border border-white/[0.05]">
                    <p className="text-xs font-black text-emerald-400/80 mb-1">{feat.label}</p>
                    <p className="text-sm text-white/65 font-medium">{feat.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S10 — FINAL CTA
      ══════════════════════════════════════════════ */}
      <section className="py-40 border-t border-white/[0.04]">
        <div className="container mx-auto px-8 text-center">
          <motion.div {...fadeUp}>
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-emerald-400/80 mb-8">Live Demonstration</p>
            <h2 className="text-5xl md:text-7xl font-black tracking-tighter mb-8 leading-[0.9]">
              Ready to Witness<br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">Optimization?</span>
            </h2>
            <p className="text-lg text-white/60 max-w-2xl mx-auto mb-14 font-medium leading-relaxed">
              Launch the Allocation Lab to trigger a complete 7-agent LangGraph pipeline run
              with Google Gemini. Every execution is unique — zero hardcoded outputs, 100% real-time
              Gen AI reasoning with full audit traceability.
            </p>
            <Link href="/simulation"
              className="inline-flex items-center gap-4 px-14 py-7 bg-gradient-to-r from-emerald-600 to-cyan-600 text-white font-black text-2xl rounded-[2rem] hover:from-emerald-500 hover:to-cyan-500 transition-all shadow-[0_30px_60px_rgba(16,185,129,0.2)] hover:scale-[1.02] active:scale-[0.98]"
            >
              Launch Allocation Lab
              <ArrowRight className="h-6 w-6" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ══════ Footer ══════ */}
      <footer className="py-16 border-t border-white/[0.04]">
        <div className="container mx-auto px-8 flex flex-col sm:flex-row justify-between items-center gap-4 text-[10px] font-black text-white/60 uppercase tracking-[0.4em]">
          <span>SmartAlloc · AI-Powered Smart Resource Allocation</span>
          <span>Powered by LangGraph.js + Google Gemini</span>
        </div>
      </footer>
    </div>
  );
}
